Repository astarte-platform/astarte_flow, pull requests merged in 2020-03, with the labels that each got.

#51 Add Github actions
  .github/dco.yml
  .github/workflows/build-workflow.yaml
  .gitlab-ci.yml
  config/ci.exs
  mix.exs
  mix.lock
Labels: chore

#52 virtual_device_pool: remove normalize_data function
  lib/astarte_flow/blocks/virtual_device_pool.ex
Labels: bug

#53 dynamic_virtual_device_pool: remove normalize_data
  lib/astarte_flow/blocks/dynamic_virtual_device_pool.ex
Labels: bug

#55 health_controller: remove unused aliases
  lib/astarte_flow_web/controllers/health_controller.ex
Labels: chore

#56 mix.exs: pull exjsonpath 0.1.0 from hex.pm
  mix.exs
  mix.lock
Labels: chore

#57 Use Skogsra for runtime configuration
  .formatter.exs
  config/config.exs
  config/releases.exs
  lib/astarte_flow/application.ex
  lib/astarte_flow/blocks/dynamic_virtual_device_pool/dets_credentials_storage.ex
  lib/astarte_flow/config.ex
  lib/astarte_flow/flows/dets_storage.ex
  lib/astarte_flow/k8s.ex
  lib/astarte_flow/pipeline_builder.ex
  lib/astarte_flow/pipelines/dets_storage.ex
  mix.exs
  mix.lock
Labels: chore

#61 Fix flaky tests
  test/astarte_flow/flows_test.exs
  test/blocks/dynamic_virtual_device_pool_test.exs
  test/blocks/virtual_device_pool_test.exs
Labels: chore, testing

#62 flows_test: ensure flow is deleted before asserting
  test/astarte_flow/flows_test.exs
Labels: chore, testing

#60 Fix dialyzer warnings
  lib/astarte_flow/blocks/device_events_producer/events_decoder.ex
  lib/astarte_flow/flows/dets_storage.ex
  mix.lock
Labels: chore

#59 CI: add elixir/OTP versions to cache keys and fix codecov
  .github/workflows/build-workflow.yaml
Labels: chore, testing

#64 README: write short description
  README.md
Labels: chore
