Repository astarte-platform/astarte_flow, pull requests merged in 2020-05, with the labels that each got.

#67 Support SSL for AMQP connections
  lib/astarte_flow/config.ex
  mix.exs
  mix.lock
Labels: enhancement

#68 Add prefetch count to AMQP channels
  lib/astarte_flow/blocks/container.ex
  lib/astarte_flow/blocks/container/rabbitmq_client.ex
  lib/astarte_flow/blocks/device_events_producer.ex
  lib/astarte_flow/blocks/device_events_producer/rabbitmq_client.ex
  lib/astarte_flow/config.ex
  lib/astarte_flow/pipeline_builder.ex
Labels: enhancement, performance

#69 Default max certificate chain length to 10
  lib/astarte_flow/blocks/mqtt_source.ex
  lib/astarte_flow/config.ex
Labels: user experience
