Repository astarte-platform/astarte_flow, pull requests merged in 2020-08, with the labels that each got.

#82 Start using PlugLoggerWithMeta
  config/config.exs
  config/dev.exs
  config/prod.exs
  config/test.exs
  lib/astarte_flow_web/endpoint.ex
  mix.exs
  mix.lock
Labels: chore

#87 Avoid failed check status on GitHub PR due to codecov bogus coverage
  codecov.yaml
Labels: chore

#89 Report errors on flow creation
  lib/astarte_flow/flows/flow.ex
  lib/astarte_flow/pipeline_builder.ex
  lib/astarte_flow/pipeline_builder/error.ex
  lib/astarte_flow_web/controllers/flow_controller.ex
  lib/astarte_flow_web/views/flow_view.ex
Labels: user experience

#90 Render blocks as object in index
  lib/astarte_flow_web/views/block_view.ex
  test/astarte_flow_web/controllers/block_controller_test.exs
Labels: API, enhancement

#91 Update astarte_device and relative deps
  mix.exs
  mix.lock
Labels: chore
