Repository astarte-platform/astarte_flow, pull requests merged in 2020-02, with the labels that each got.

#6 Add container and astarte_devices_source to pipeline builder
  config/config.exs
  lib/astarte_streams/pipeline_builder.ex
Labels: enhancement

#20 LuaMapper: add string_utils
  lib/astarte_flow/blocks/lua_mapper.ex
Labels: enhancement

#22 PipelineBuilder: fix missing eval
  lib/astarte_flow/pipeline_builder.ex
Labels: bug

#30 Add support to object aggregated
  lib/astarte_flow/blocks/device_events_producer/events_decoder.ex
  test/blocks/device_events_producer_test.exs
Labels: enhancement

#36 Add minimal flow validation
  lib/astarte_flow/flows/flow.ex
  test/astarte_streams/flows_test.exs
Labels: minor, user experience

#35 Container type
  lib/astarte_flow/blocks/container.ex
  lib/astarte_flow/blocks/container/amqp_client.ex
  lib/astarte_flow/blocks/container/rabbitmq_client.ex
  lib/astarte_flow/k8s.ex
  lib/astarte_flow/pipeline_builder.ex
Labels: enhancement, user experience

#45 random_producer: add delay_ms option
  lib/astarte_flow/blocks/random_producer.ex
  lib/astarte_flow/pipeline_builder.ex
Labels: enhancement

#49 Add .tool-versions file
  .tool-versions
Labels: chore

#50 Bump Elixir version in Dockerfile and add .dockerignore
  .dockerignore
  Dockerfile
Labels: chore
