Repository astarte-platform/astarte_flow, pull requests merged in 2021-02, with the labels that each got.

#97 Add user documentation to Astarte Flow
  guides/0002-flow-messages.md
  guides/0010-defining-a-pipeline.md
  guides/0110-http_source.md
  mix.exs
  mix.lock
Labels: blocking, documentation

#98 doc: add container block documentation
  guides/0111-container.md
Labels: documentation

#105 Add more links
  README.md
  guides/core_concepts/0001-overview.md
Labels: documentation

#101 Add doc pages for pipeline blocks
  guides/0113-random_source.md
  guides/0114-json_mapper.md
  guides/0115-filter.md
  guides/0116-http_sink.md
Labels: documentation

#107 Add mqtt_source's JSON schema to default blocks
  priv/blocks/mqtt_source.json
Labels: enhancement

#100 doc: add documentation for additional blocks
  guides/blocks/0112-lua_map.md
  guides/blocks/0117-sort.md
  guides/blocks/0118-json_path_map.md
  guides/blocks/0119-split_map.md
Labels: documentation

#109 Move blocks mark down pages to guides/blocks dir
  guides/blocks/0113-random_source.md
  guides/blocks/0114-json_mapper.md
  guides/blocks/0115-filter.md
  guides/blocks/0116-http_sink.md
Labels: documentation

#110 Add Installing and Running a pipeline
  guides/core_concepts/0010-defining-a-pipeline.md
Labels: documentation

#113 http_source: handle headers passed as map
  lib/astarte_flow/blocks/http_source.ex
Labels: bug

#111 doc: add Blocks page
  guides/core_concepts/0001-overview.md
  guides/core_concepts/0003-blocks.md
Labels: documentation

#115 doc: add Pipelines page
  guides/core_concepts/0001-overview.md
  guides/core_concepts/0004-pipelines.md
Labels: documentation

#114 doc: add Flow documentation page
  guides/core_concepts/0001-overview.md
  guides/core_concepts/0005-flows.md
Labels: documentation

#116 doc: add more links to existing pages
  guides/core_concepts/0002-flow-messages.md
  guides/core_concepts/0003-blocks.md
Labels: documentation

#117 doc: add Streams documentation
  guides/core_concepts/0001-overview.md
  guides/core_concepts/0006-streams.md
Labels: documentation

#118 doc: add astarte_devices_source block documentation
  guides/blocks/0120-astarte_devices_source.md
Labels: documentation

#119 doc: add mqtt_source block documentation
  guides/blocks/0120-mqtt_source.md
Labels: documentation

#120 0112-lua_map.md: fix example script
  guides/blocks/0112-lua_map.md
Labels: documentation

#121 doc: remove order number from blocks page names
  guides/blocks/astarte_devices_source.md
  guides/blocks/container.md
  guides/blocks/filter.md
  guides/blocks/http_sink.md
  guides/blocks/http_source.md
  guides/blocks/json_mapper.md
  guides/blocks/json_path_map.md
  guides/blocks/lua_map.md
  guides/blocks/mqtt_source.md
  guides/blocks/random_source.md
  guides/blocks/sort.md
  guides/blocks/split_map.md
  guides/blocks/virtual_device_pool.md
  guides/core_concepts/0001-overview.md
Labels: documentation

#122 doc: add pipeline builder documentation
  guides/assets/images/pipeline-editor-block-options.png
  guides/assets/images/pipeline-editor-pipeline-source.png
  guides/assets/images/pipeline-editor-visual-graph.png
  guides/core_concepts/0001-overview.md
  guides/core_concepts/0020-pipeline-editor.md
  mix.exs
Labels: documentation

#124 container: add image_pull_secrets property
  guides/blocks/container.md
  lib/astarte_flow/blocks/container.ex
  lib/astarte_flow/k8s.ex
  lib/astarte_flow/pipeline_builder.ex
Labels: enhancement

#126 Add mqtt_sink block
  guides/blocks/mqtt_sink.md
  lib/astarte_flow/blocks/mqtt_sink.ex
  priv/blocks/mqtt_sink.json
Labels: enhancement

#129 Add modbus_tcp_source
  guides/blocks/modbus_tcp_source.md
  lib/astarte_flow/blocks/modbus_tcp_source.ex
  mix.exs
  mix.lock
  priv/blocks/modbus_tcp_source.json
Labels: enhancement

#128 to_json: make it work again and add support to JSONTemplate
  guides/blocks/to_json.md
  lib/astarte_flow/blocks/json_mapper.ex
  mix.exs
  mix.lock
  priv/blocks/to_json.json
  test/blocks/json_mapper_test.exs
Labels: bug, enhancement

#130 mqtt_sink: fix missing handler and handle_info
  lib/astarte_flow/blocks/mqtt_sink.ex
Labels: bug

#132 Add update_metadata block
  guides/blocks/update_metadata.md
  lib/astarte_flow/blocks/update_metadata.ex
  priv/blocks/update_metadata.json
Labels: enhancement

#134 lua_mapper: fix: Float.round fails on integer
  lib/astarte_flow/blocks/lua_mapper.ex
Labels: bug

#135 modbus_tcp_source: fix: floating point numbers are called real
  lib/astarte_flow/blocks/modbus_tcp_source.ex
Labels: bug

#133 update_metadata: remove debug print
  lib/astarte_flow/blocks/update_metadata.ex
Labels: chore

#136 Add custom CA and mutual SSL authentication to MQTT blocks
  guides/blocks/mqtt_sink.md
  guides/blocks/mqtt_source.md
  lib/astarte_flow/blocks/mqtt_sink.ex
  lib/astarte_flow/blocks/mqtt_source.ex
  priv/blocks/mqtt_sink.json
  priv/blocks/mqtt_source.json
Labels: enhancement

#137 default_blocks: fix external_resource path
  lib/astarte_flow/blocks/default_blocks.ex
Labels: chore

#138 modbus_tcp_source: handle all target validation failures
  lib/astarte_flow/blocks/modbus_tcp_source.ex
Labels: bug, user experience
